// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Runtime;

namespace AirgiCook.Domain.Models.Data
{
    public partial class Project: ICloneable
    {
        public Project(int id, string name, DateTime createdDate, DateTime? modifiedDate, string version, int? editorId, int? recipientId, int? extraction, int? compensationHotte, int? compensationDiffusion, string createdUserId, bool? active, string comments, Actor editor, Actor recipient, ICollection<Local> locals)
        {
            Id = id;
            Name = name;
            CreatedDate = createdDate;
            ModifiedDate = modifiedDate;
            Version = version;
            EditorId = editorId;
            RecipientId = recipientId;
            Extraction = extraction;
            CompensationHotte = compensationHotte;
            CompensationDiffusion = compensationDiffusion;
            CreatedUserId = createdUserId;
            Active = active;
            Comments = comments;
            Editor = editor;
            Recipient = recipient;
            Locals = locals;
        }
        public Project(Project project)
        {
            Id = project.Id;
            Name = project.Name;
            CreatedDate = project.CreatedDate;
            ModifiedDate = project.ModifiedDate;
            Version = project.Version;
            EditorId = project.EditorId;
            RecipientId = project.RecipientId;
            Extraction = project.Extraction;
            CompensationHotte = project.CompensationHotte;
            CompensationDiffusion = project.CompensationDiffusion;
            CreatedUserId = project.CreatedUserId;
            Active = project.Active;
            Comments = project.Comments;
            Editor = project.Editor;
            Recipient = project.Recipient;
            Locals = project.Locals;
        }
        public object Clone()
        {
            //Project clone = (Project)this.MemberwiseClone();
            //clone.Editor = this.Editor;
            //clone.Recipient = this.Recipient;
            //clone.Locals = this.Locals;
            //clone.Active = this.Active;
            //return clone;
            return new Project(this);   
        }
    }
}